apiVersion: v1
kind: Service
metadata:
  name: obvestilni-service
  labels:
    app: obvestilni-sistem
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: obvestilni-sistem